server {
    listen 8080;
    server_name localhost;

    # Frontend dev
    location / {
        proxy_pass http://10.14.1.223:5173/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Backend
    location /api/ {
        proxy_pass http://10.14.1.223:3001/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
    }

    # Revealjs backend
    location /revealjsapi/ {
        proxy_pass http://10.14.1.223:8080/revealjsapi/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
    }

}
